<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findAllArticlesPaginated($first, $max)
    {
        $dql = "SELECT art, aut, cat, tags, com
                FROM AppBundle:Article art
                JOIN art.author aut
                JOIN art.category cat
                JOIN art.tags tags
                LEFT JOIN art.comments com
                ORDER BY art.createdAt DESC";
        $query = $this->getEntityManager()->createQuery($dql)->setFirstResult($first)->setMaxResults($max);

        return new Paginator($query);
    }

    public function findArticleBySlug($slug)
    {
        $dql = "SELECT art, aut, cat, tags, com
                FROM AppBundle:Article art
                JOIN art.author aut
                JOIN art.category cat
                JOIN art.tags tags
                LEFT JOIN art.comments com
                WHERE art.slug = :slug";
        $query = $this->getEntityManager()->createQuery($dql)->setParameter('slug', $slug)->getOneOrNullResult();

        return $query;
    }

    public function findTopArticlesByRating()
    {
        $dql = "SELECT art
                FROM AppBundle:Article art
                ORDER BY art.ratingCounter / art.viewsCounter DESC";
        $query = $this->getEntityManager()->createQuery($dql)->setFirstResult(0)->setMaxResults(5)->getResult();

        return $query;
    }
}
