<?php

namespace AppBundle\Repository;

/**
 * ArticeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticeRepository extends \Doctrine\ORM\EntityRepository
{
}
