<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findAllArticlesPaginated($first, $max)
    {
        $dql = "SELECT art, aut, cat, tags
                FROM AppBundle:Article art
                JOIN art.author aut
                JOIN art.category cat
                JOIN art.tags tags
                ORDER BY art.createdAt DESC";

        return new Paginator($this->getEntityManager()->createQuery($dql)->setFirstResult($first)->setMaxResults($max));
    }

    public function findArticleBySlug($slug)
    {
        $dql = "SELECT art
                FROM AppBundle:Article art
                WHERE art.slug = :slug";
        return $this->getEntityManager()->createQuery($dql)->setParameter('slug', $slug)->getOneOrNullResult();
    }
}
