<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository
{
    public function findAllAutorsPaginated($first, $max)
    {
        $dql = "SELECT au
                FROM AppBundle:Author au
                LEFT JOIN au.articles ar
                ORDER BY au.createdAt DESC";
        $query = $this->getEntityManager()
            ->createQuery($dql)
            ->setFirstResult($first)
            ->setMaxResults($max);

        return new Paginator($query);
    }
}
