<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findAllCategoriesASC()
    {
        $dql = "SELECT ca
                FROM AppBundle:Category ca
                ORDER BY ca.name ASC";
        $query = $this->getEntityManager()->createQuery($dql)->getResult();

        return $query;
    }
}
