<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findAllCategoriesPaginated($first, $max)
    {
        $dql = "SELECT ca
                FROM AppBundle:Category ca
                LEFT JOIN ca.articles ar
                ORDER BY ca.createdAt DESC";
        $query = $this->getEntityManager()->createQuery($dql)->setFirstResult($first)->setMaxResults($max);

        return new Paginator($query);
    }

    public function findAllCategoriesASC()
    {
        $dql = "SELECT ca
                FROM AppBundle:Category ca
                ORDER BY ca.name ASC";
        $query = $this->getEntityManager()->createQuery($dql)->getResult();

        return $query;
    }
}
