<?php

namespace AppBundle\Repository;

/**
 * CommentatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentatorRepository extends \Doctrine\ORM\EntityRepository
{
}
