<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CommentatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentatorRepository extends EntityRepository
{
    public function findAllCommentatorsPaginated($first, $max)
    {
        $dql = "SELECT cr
                FROM AppBundle:Commentator cr
                JOIN cr.comments co
                ORDER BY cr.createdAt DESC";
        $query = $this->getEntityManager()->createQuery($dql)->setFirstResult($first)->setMaxResults($max);

        return new Paginator($query);
    }
}
