<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function findAllTagsPaginated($first, $max)
    {
        $dql = "SELECT t
                FROM AppBundle:Tag t
                LEFT JOIN t.articles ar
                ORDER BY t.createdAt DESC";
        $query = $this->getEntityManager()
            ->createQuery($dql)
            ->setFirstResult($first)
            ->setMaxResults($max);

        return new Paginator($query);
    }

}
