security:

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 13
        AppBundle\Entity\Author:
                    algorithm: bcrypt
                    cost: 13

    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    Admin:
                        password: $2y$13$hoAgB0dFJfXt6fSpGDPkAeyS3rB2gK9oo4qgIcAWgI0FvVrXoS61y
                        roles: 'ROLE_SUPER_ADMIN'
        user_db:
            entity: { class: AppBundle\Entity\Author, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            anonymous: ~

            form_login:
                login_path: /login
                check_path: /login_check

            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/admin/user, roles: ROLE_SUPER_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]